// Problem Statement:
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function getSumOfEvenFibonacci(n){
	var a = 1, b = 2, f = 3, arr = [1,2];
	while (f <= n){
		f = a + b;
		a = b;
		b = f;
		if(f < n){
			arr.push(f);
		}
	}
	return arr.filter(function(a){return a%2==0}).reduce(function(a,b){return a+b});
}